#服务的名称
spring:
  rabbitmq:
    host: 106.12.195.50
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://106.12.195.50:9411
  sleuth:
    sampler:
      probability: 1

#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8772
      
env: dev2018
branch: master
