#服务的名称
spring:
  rabbitmq:
    host: 10.7.227.233
    port: 5672
    username: guest
    password: guest

#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8772

spring:
  zipkin:
    base-url: http://10.7.227.233:9411
  sleuth:
    sampler:
      probability: 1
      
env: dev
branch: master
