#服务的名称
spring:
  rabbitmq:
    host: 10.7.232.99
    port: 5672
    username: guest
    password: guest

#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8772

#制定注册中心地址，进行服务注册（集群--高可用）
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: product-service
  zipkin:
    base-url: http://10.7.232.99:9411
  sleuth:
    sampler:
      probability: 1
      
env: dev
branch: master
