server:
  port: 8771

#制定注册中心地址，进行服务注册（集群--高可用）
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: product-service
  zipkin:
    base-url: http://10.7.232.99:9411
  sleuth:
    sampler:
      probability: 1
      
env: test
branch: test
